language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  matrix:
    #- DB=mysql
    #- DB=pgsql
    - DB=sqlite

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:1.0.*"
  - travis_retry composer global require "codeception/codeception:2.0.*"
  - travis_retry composer install --no-interaction --prefer-dist

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
  #- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS yii2_eav_test;" -uroot; fi
  #- if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS yii2_eav_test;" -U postgres; fi
  #- if [[ "$DB" == "pgsql" ]]; then psql -c "create database yii2_eav_test;" -U postgres; fi
  #- cd tests
  #- php codeception/_app/yii migrate/up --interactive=0
  #- php codeception/_app/yii migrate/up --migrationPath=../src/migrations --interactive=0
  - ~/.composer/vendor/bin/codecept build

script:
  - ~/.composer/vendor/bin/codecept run --coverage-html --coverage-xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/report.xml

after_failure:
  #- cat tests/_app/runtime/logs/*
  - cat tests/_output/*
